DailyBasket.Franchisee/Controllers/UserMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Controllers
{
    [ChildActionOnly]
    public class UserMenuController : Controller
    {
        // GET: UserMenu
        public ActionResult Master()
        {
            return View("UserMenu/_Master");
        }

        
        public ActionResult Purchase_Manager()
        {
            return View("UserMenu/_PurchaseManager");
        }

        
        public ActionResult Sale_Manager()
        {
            return View("UserMenu/_SaleManager");
        }

        
        public ActionResult Account_Manger()
        {
            return View("UserMenu/_AccountManager");
        }

        
        public ActionResult Delivery()
        {
            return View("UserMenu/_Delivery");
        }

        
        public ActionResult Partner()
        {
            return View("UserMenu/_Partner");
        }

        
        public ActionResult Inverstor()
        {
            return View("UserMenu/_Inverstor");
        }
    }
}

DailyBasket.Franchisee/Views/Shared/_DailyBasketLayout.cshtml
@using System.Web.Optimization
@using DailyBasket.Franchisee.Helper
@*@using DailyBasket.Franchisee.Core.Enum*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - DailyBaskets </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    @Styles.Render("~/bundles/css/bootstrap")
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DailyBasket, Layout -->
    @Styles.Render("~/bundles/css/dailybasket", "~/bundles/css/layout")
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Dashboard", new { Area = "" })" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>D</b>BT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>@SessionManager.CurrentUserName</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="hidden-xs">@SessionManager.CurrentFranchiseeName</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                
                <ul class="sidebar-menu">
                    <li class="header">Main Navigation</li>
                    <li><a href="@Url.Action("Index", "Dashboard", new { Area = "" })"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
                    
                    @Html.Action(SessionManager.CurrentUserType, "UserMenu", new { Area = "" })

                    <li class="treeview">
                        <a href="@Url.Action("Logout", "Account", new { Area = "" })">
                            <i class="fa fa-table"></i> <span>Logout</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                    </li>
                    
                </ul>
                <!-- /.sidebar -->
            </section>
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">

                @RenderBody()


            </section>

            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <strong> Powered By <a href="http://www.softeligent.net" target="_blank"> Softeligent Technologies Pvt. Ltd.</a> </strong>
            </div>
            <strong>
                Copyright &copy; @DateTime.Now.Year <a href="#" target="_blank"> Dailybaskets.</a>&nbsp;&nbsp;All rights Reserved.
            </strong>
        </footer>

        <div class="control-sidebar-bg"></div>
    </div>
    @Scripts.Render("~/bundles/script/bootstrap-ui")
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);

        /*window.onunload = function () {
            debugger;
            $.get(window.location.origin + '/Account/ClearAllBrowserCookie', function () {
                alert("All Cookie Cleared...");
            });
        }*/
    </script>
    @Scripts.Render("~/bundles/script/layout", "~/bundles/script/bootstrap", "~/bundles/script/moment")
</body>
</html>