DailyBasket.Franchisee/Areas/Sale/Controllers/CustomerOrdersController.cs
using DailyBasket.Franchisee.Areas.Sale.BLL;
using DailyBasket.Franchisee.Areas.Sale.Models.ViewModels;
using DailyBasket.Franchisee.Core.Enum;
using DailyBasket.Franchisee.Core.Interface.BLL.Sale;
using DailyBasket.Franchisee.Helper;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace DailyBasket.Franchisee.Areas.Sale.Controllers
{
    [Authorize]
    public class CustomerOrdersController : Controller
    {
        private ICustomerOrders iCustomerOrdersBLL = new CustomerOrdersBLL();
        // GET: CustomerOrders/CustomerOrders
        public ActionResult InProcessOrders()
        {
            ViewBag.MethodName = "InProcessOrder";
            ViewBag.PageTitle = "In Process Customer Orders";
            return View("customerOrders", GetCustomerOrders(OrderStatus.InProcess));
        }

        public ActionResult ReadytoDispatchOrders()
        {
            ViewBag.MethodName = "ReadytoDispatchOrder";
            ViewBag.PageTitle = "Ready to Dispatch Customer Orders";
            return View("customerOrders", GetCustomerOrders(OrderStatus.ReadyToDispatch));
        }

        public ActionResult DispatchedOrders()
        {
            ViewBag.MethodName = "DispatchedOrder";
            ViewBag.PageTitle = "Dispatch Customer Orders";
            return View("customerOrders", GetCustomerOrders(OrderStatus.Dispatched));
        }

        public ActionResult DeliveredOrders()
        {
            ViewBag.MethodName = "DeliveredOrder";
            ViewBag.PageTitle = "Delivered Customer Orders";
            return View("customerOrders", GetCustomerOrders(OrderStatus.Delivered));
        }

        public ActionResult CancelledOrders()
        {
            ViewBag.MethodName = "CancelledOrder";
            ViewBag.PageTitle = "Cancelled Customer Orders";
            return View("customerOrders", GetCustomerOrders(OrderStatus.Cancelled));
        }

        public ActionResult InProcessOrder(ulong coId = 0)
        {
            ViewBag.PageTitle = "In Process Customer Order";
            ViewBag.Url = "ChangeCurrentOrderStatus";
            CustomerOrdersViewModels customerOrderModelView = GetCustomerOrder(OrderStatus.InProcess, coId);
            if (customerOrderModelView == null)
                return RedirectToAction("InProcessOrders");
            customerOrderModelView.Status = OrderStatus.InProcess;
            BindOrderStatusDdlList(OrderStatus.InProcess);
            return View("customerOrder", customerOrderModelView);
        }

        public ActionResult ReadytoDispatchOrder(ulong coId = 0)
        {
            ViewBag.PageTitle = "Ready to Dispatch Customer Order";
            ViewBag.Url = "ChangeCurrentOrderStatus";
            CustomerOrdersViewModels customerOrderModelView = GetCustomerOrder(OrderStatus.ReadyToDispatch, coId);
            if (customerOrderModelView == null)
                return RedirectToAction("ReadytoDispatchOrders");
            customerOrderModelView.Status = OrderStatus.ReadyToDispatch;
            BindOrderStatusDdlList(OrderStatus.ReadyToDispatch);
            return View("customerOrder", customerOrderModelView);
        }

        public ActionResult DispatchedOrder(ulong coId = 0)
        {
            ViewBag.PageTitle = "Dispatch Customer Order";
            ViewBag.Url = "ChangeCurrentOrderStatus";
            CustomerOrdersViewModels customerOrderModelView = GetCustomerOrder(OrderStatus.Dispatched, coId);
            if (customerOrderModelView == null)
                return RedirectToAction("DispatchedOrders");
            customerOrderModelView.Status = OrderStatus.Dispatched;
            ViewBag.CodPaymentModeList = EnumDropdownlistHelper.GetEnumCashOnDeliveryPMList();
            BindOrderStatusDdlList(OrderStatus.Dispatched);
            return View("customerOrder", customerOrderModelView);
        }

        public ActionResult DeliveredOrder(ulong coId = 0)
        {
            ViewBag.PageTitle = "Delivered Customer Order";
            ViewBag.Url = "UpdateReturnGoods";
            CustomerOrdersViewModels customerOrderModelView = GetCustomerOrder(OrderStatus.Delivered, coId);
            if (customerOrderModelView == null)
                return RedirectToAction("DeliveredOrders");
            customerOrderModelView.Status = OrderStatus.Delivered;
            BindOrderStatusDdlList(OrderStatus.Delivered);
            return View("customerOrder", customerOrderModelView);
        }

        public ActionResult CancelledOrder(ulong coId = 0)
        {
            ViewBag.PageTitle = "Cancelled Customer Order";
            ViewBag.Url = null;
            CustomerOrdersViewModels customerOrderModelView = GetCustomerOrder(OrderStatus.Cancelled, coId);
            if (customerOrderModelView == null)
                return RedirectToAction("CancelledOrders");
            customerOrderModelView.Status = OrderStatus.Cancelled;
            BindOrderStatusDdlList(OrderStatus.Cancelled);
            return View("customerOrder", customerOrderModelView);
        }

        private List<CustomerOrdersViewModels> GetCustomerOrders(OrderStatus orderStatus)
        {
            return iCustomerOrdersBLL.GetCustomerOrders(orderStatus, SessionManager.CurrentUserId);
        }

        private CustomerOrdersViewModels GetCustomerOrder(OrderStatus orderStatus, ulong coId)
        {
            return iCustomerOrdersBLL.GetCustomerOrder(coId, orderStatus, SessionManager.CurrentUserId);
        }

        private CustomerOrdersViewModels GetCustomerOrderWithReturnGoods(OrderStatus orderStatus, ulong coId)
        {
            return iCustomerOrdersBLL.GetCustomerOrderWithReturnGoods(coId, orderStatus);
        }

        private void BindOrderStatusDdlList(OrderStatus orderStatusId)
        {
            ViewBag.OrderStatusDdlList = iCustomerOrdersBLL.GetActiveOrderStatusDdlList((uint)(orderStatusId));
        }

        [HttpPost]
        public ActionResult UpdateReturnGoods(string[] returnProduct, CustomerOrdersViewModels customerOrderVM)
        {
            string completeUrl = Request.UrlReferrer.AbsolutePath.ToString();
            string[] arrayUrl = new string[4];
            arrayUrl = completeUrl.Split('/');
            if (returnProduct != null)
            {
                iCustomerOrdersBLL.ChangeCurrentOrderStatusofReturnProducts(returnProduct);
            }
            return RedirectToAction(arrayUrl[3], new { coId = customerOrderVM.Id}); // Redirect to current page
            //return RedirectToAction(arrayUrl[3] + "s");  // Redirect to last request
        }

        //Change Status of Current Order 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeCurrentOrderStatus(CustomerOrdersViewModels customerOrderVM, string CodPaymentMode)
        {
            // Array for Complete Product Path
 
            string completeUrl = Request.UrlReferrer.AbsolutePath.ToString();
            string[] arrayUrl = new string[4];
            arrayUrl = completeUrl.Split('/');
            if (ModelState.IsValid)
            {
                if (iCustomerOrdersBLL.ChangeOrderStatus(customerOrderVM.Id, customerOrderVM.OrderStatusId, SessionManager.CurrentUserId) != 0)
                {
                    if(customerOrderVM.OrderStatusId == (uint)OrderStatus.Delivered)
                    {
                        // Add Loyalty Points
                        iCustomerOrdersBLL.UpdateCustomerLoyaltyPoints(customerOrderVM.Id, (uint)OrderStatus.Delivered);
                        // Update Cash On Delivery Payment Mode
                        if(CodPaymentMode != null || !CodPaymentMode.Equals(CashOnDeliveryPaymentMode.NA))
                        {
                            iCustomerOrdersBLL.UpdateCustomerOrderCodPaymentMode(customerOrderVM.Id, CodPaymentMode);
                        }
                    }
                    
                    // Restore Product Stock
                    if (customerOrderVM.OrderStatusId == (uint)OrderStatus.Cancelled)
                    {
                        iCustomerOrdersBLL.RevertProductsStock(customerOrderVM.Id, (uint)OrderStatus.Cancelled, SessionManager.CurrentUserId);
                    }

                    return RedirectToAction(arrayUrl[3] + "s");  // Redirect to last request
                }
                else
                {
                    TempData["Message"] = "Order Status not Updated successfully, Please try again!";
                    TempData["CssClass"] = "text-success";
                    return RedirectToAction(arrayUrl[3]); // Redirect to current page
                }
            }
            return View(arrayUrl[3]);
        }

        //[HttpPost]
        public ActionResult PrintOrder(ulong orderId = 0, ulong orderStatus = 0)
        {
            CustomerOrdersViewModels customerOrderModelView = null;
            if(orderId != 0)
                customerOrderModelView = iCustomerOrdersBLL.GetCustomerOrderToPrint(orderId, orderStatus, SessionManager.CurrentUserId);
            return View(customerOrderModelView);
        }

        public string RenderRazorViewToString(ulong orderId)
        {
            CustomerOrdersViewModels customerOrderModelView = GetCustomerOrder(OrderStatus.ReadyToDispatch, orderId);
            ViewData["certificate"] = customerOrderModelView;

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, "PrintOrder");
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);

                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);

                return sw.GetStringBuilder().ToString();
            }
        }

        //public int ChangeCurrentOrderStatusofReturnProducts(ulong prodId = 0, ulong coId = 0, ulong spId = 0)
        //{

DailyBasket.Franchisee/Areas/Stock/Controllers/StockProductController.cs
using DailyBasket.Franchisee.Areas.ProductMaster.BLL;
using DailyBasket.Franchisee.Areas.Stock.BLL;
using DailyBasket.Franchisee.Areas.Stock.Models.ViewModels;
using DailyBasket.Franchisee.Core.Interface.BLL.Stock;
using DailyBasket.Franchisee.Core.Model.Stock;
using DailyBasket.Franchisee.Helper;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Franchisee.Areas.Stock.Controllers
{
    [Authorize]
    public class StockProductController : Controller
    {
        // GET: Sale/StockProduct
        IStockProduct istockProductBLL = null;
        public StockProductController()
        {
            istockProductBLL = new StockProductBLL();
        }

        public ActionResult Index()
        {
            return RedirectToAction("AvailableStocks");
        }

        public ActionResult AvailableStocks()
        {
            List<StockProductViewModel> stockProductVMList = istockProductBLL.GetProductsStock(SessionManager.CurrentUserId);
            return View("ProductsStock", stockProductVMList);
        }


        public ActionResult ExpiryWiseProductStock(ulong ProductId = 0)
        {
            if (ProductId != 0)
            {
                List<StockProductViewModel> stockProductVMList = istockProductBLL.GetExpiryWiseProductsStock(ProductId, SessionManager.CurrentUserId);
                return View("ExpiryWiseProductStock", stockProductVMList);
            }
            return RedirectToAction("Index");
        }

        public ActionResult BatchWiseProductStock(ulong ProductId = 0)
        {
            List<StockProductViewModel> stockProductVMList = null;
            if (ProductId != 0)
            {
                stockProductVMList = istockProductBLL.GetBatchWiseProductStock(ProductId, SessionManager.CurrentUserId);
            }
            ViewBag.ProductDdlList = new ProductBLL().GetActiveProdListDdl();
            return View(stockProductVMList);
        }

        [HttpGet]
        public ActionResult UpdateProductSaleRate(ulong fcpoId = 0, ulong spId = 0)
        {
            if (spId != 0)
            {
                StockProductSaleRateModel stockProductModel = istockProductBLL.GetBatchWiseProductSaleRateToUpdate(fcpoId, spId, SessionManager.CurrentUserId);
                return View("UpdateBatchWiseProductSaleRate", stockProductModel);
            }
            return RedirectToAction("BatchWiseProductStock");
        }
        
        [HttpPost]
        public ActionResult UpdateProductSaleRate(StockProductSaleRateModel stockProductModel)
        {
            if (ModelState.IsValid)
            {
                if (istockProductBLL.UpdateBatchWiseProductSaleRate(stockProductModel, SessionManager.CurrentUserId) != 0)
                    return RedirectToAction("BatchWiseProductStock", new { ProductId = stockProductModel.ProductId });
                TempData["Message"] = "Oop's error occured! Try again";
            }
            StockProductSaleRateModel stockProductModelBackup = istockProductBLL.GetBatchWiseProductSaleRateToUpdate(stockProductModel.PopId, stockProductModel.SpId, SessionManager.CurrentUserId);
            if (stockProductModelBackup != null)
            {
                stockProductModel.ProductName = stockProductModelBackup.ProductName;
                stockProductModel.PurchaseRate = stockProductModelBackup.PurchaseRate;
                stockProductModel.AvailableStock = stockProductModelBackup.AvailableStock;
                stockProductModel.BatchNo = stockProductModelBackup.BatchNo;
                stockProductModel.ExpiryDate = stockProductModelBackup.ExpiryDate;
                stockProductModel.PackagingDate = stockProductModelBackup.PackagingDate;
                return View("UpdateBatchWiseProductSaleRate", stockProductModel);
            }
            return RedirectToAction("BatchWiseProductStock", new { ProductId = stockProductModel.ProductId });
        }

    }
}

DailyBasket.Franchisee/Controllers/UserMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Controllers
{
    [ChildActionOnly]
    public class UserMenuController : Controller
    {
        // GET: UserMenu
        public ActionResult Master()
        {
            return View("UserMenu/_Master");
        }

        
        public ActionResult Purchase_Manager()
        {
            return View("UserMenu/_PurchaseManager");
        }

        
        public ActionResult Sale_Manager()
        {
            return View("UserMenu/_SaleManager");
        }

        
        public ActionResult Account_Manger()
        {
            return View("UserMenu/_AccountManager");
        }

        
        public ActionResult Delivery()
        {
            return View("UserMenu/_Delivery");
        }

        
        public ActionResult Partner()
        {
            return View("UserMenu/_Partner");
        }

        
        public ActionResult Inverstor()
        {
            return View("UserMenu/_Inverstor");
        }
    }
}

DailyBasket.Franchisee/Views/Shared/UserMenu/_AccountManger.cshtml
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Product Master</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Brand</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddBrand", "Brand", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("BrandList", "Brand", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Vendor</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddVendor", "Vendor", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("VendorList", "Vendor", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Main Category</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddMainCategory", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("MainCategoryList", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>SubCategory</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddSubCategory", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("SubCategoryList", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Products</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li class="treeview">
                    <a href="@Url.Action("AddProductHsnNumber", "Product", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add HSN Number</a>
                    <a href="@Url.Action("AddProduct", "Product", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add Product</a>
                    <a href="@Url.Action("ProductList", "Product", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a>
                </li>
            </ul>
        </li>

    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Purchase Entry</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("AddPurchaseOrder", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> New Entry</a></li>
        <li><a href="@Url.Action("PendingPurchaseEntries", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> Pending Entries</a></li>
        <li><a href="@Url.Action("ViewPurchaseOrders", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> Purchase History</a></li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Stock</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("AvailableStocks", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Products Stock</a></li>
        <li><a href="@Url.Action("BatchWiseProductStock", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Batchwise Product Stock</a></li>
        <li><a href="@Url.Action("ViewExpiryWiseConvetableProducts", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Convertable Products</a></li>
        <li><a href="@Url.Action("ReorderProductsSystem", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Reorder System</a></li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Customer Orders</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("InProcessOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Pending Orders</a></li>
        <li><a href="@Url.Action("ReadyToDispatchOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Ready to Dispatch</a></li>
        <li><a href="@Url.Action("DispatchedOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Dispatched</a></li>
        <li><a href="@Url.Action("DeliveredOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Delivered</a></li>
        <li><a href="@Url.Action("CancelledOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Cancelled</a></li>
    </ul>
</li>

DailyBasket.Franchisee/Views/Shared/UserMenu/_Master.cshtml
<li class="treeview">
        <a href="#">
            <i class="fa fa-table"></i> <span>Franchisee Customers</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("", "", new { Area = "" })"><i class="fa fa-circle-o"></i> Customers</a></li>
        </ul>
       
    </li>
  
    <li class="treeview">
        <a href="#">
            <i class="fa fa-table"></i> <span>Purchase Entry</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("AddPurchaseProductOrder", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> New Entry</a></li>
            <li><a href="@Url.Action("MyPurchaseOrders", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> My Orders</a></li>
        </ul>
        <ul class="treeview-menu">
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Purchase History</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("DeliveredOrders", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> Received</a></li>
                    <li><a href="@Url.Action("CancelledOrders", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> Cancelled</a></li>
                </ul>
            </li>
           
        </ul>
    </li>
   <li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Stock</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("AvailableStocks", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Products Stock</a></li>
        <li><a href="@Url.Action("BatchWiseProductStock", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Batchwise Product Stock</a></li>
    </ul>
</li>
   <li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Customer Orders</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("InProcessOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Pending Orders</a></li>
        <li><a href="@Url.Action("ReadyToDispatchOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Ready to Dispatch</a></li>
        <li><a href="@Url.Action("DispatchedOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Dispatched</a></li>
        <li><a href="@Url.Action("DeliveredOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Delivered</a></li>
        <li><a href="@Url.Action("CancelledOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Cancelled</a></li>
    </ul>
</li>

    <li class="treeview">
        <a href="#">
            <i class="fa fa-table"></i> <span>Reports</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("Purchase", "Purchase", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Purchase Report</a></li>
            <li><a href="@Url.Action("Sales", "Sale", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Sales Report</a></li>
            <li><a href="@Url.Action("Stock", "Stock", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Stock Report</a></li>
        </ul>
    </li>