DailyBasket.Franchisee/Areas/Sale/Models/ViewModels/CustomerOrderProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DailyBasket.Franchisee.Areas.Sale.Models.ViewModels
{
    public class CustomerOrderProductViewModel
    {
        public ulong Id { get; set; }
        public string ProductName { get; set; }
        public float Quantity { get; set; }
        public double TotalAmount { get; set; }
        public string Expiry_Date { get; set; }
        public float Mrp { get; set; }
        public float Sale_Rate { get; set; }
        public string Barcode { get; set; }
        public ulong IsReturnProduct { get; set; }
        public ulong SpId { get; set; }
        public ulong Cop_Id { get; set; }
    }
}

DailyBasket.Franchisee/Areas/Sale/Models/ViewModels/CustomerOrdersViewModels.cs
using DailyBasket.Franchisee.Core.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DailyBasket.Franchisee.Areas.Sale.Models.ViewModels
{
    public class CustomerOrdersViewModels
    {
        public ulong Id { get; set; }

        public string FranchiseeName { get; set; }
        public string Gstin { get; set; }
        public string FAddress { get; set; }
        public string FCity { get; set; }
        public string FState { get; set; }
        public string FMobile { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public double OrderAmount { get; set; }
        public string OrderDate { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string DeliveryBoyName { get; set; }
        public string GstNo { get; set; }
        public string TransactionId { get; set; }
        public string PaymentMode { get; set; }

        //Cash On Delivery Payment Mode - Cash/Card
        public string CodPaymentMode { get; set; }
        public string OrderPaymentStatus { get; set; }

        /*********** Invoice Fields Start ***********/
        public double SavingAmount { get; set; } 
        public float GstAmount { get; set; }
        public uint QuantityCount { get; set; }
        public float DeliveryCharges { get; set; }
        public float ExtraCharges { get; set; }
        public double ProductTotalAmount { get; set; }
        public double ProductTotalAmountofReturnGoods { get; set; }
        /*********** Invoice Fields End ************/
        public uint OrderStatusId { get; set; }
        public OrderStatus Status { get; set; }
        public List<CustomerOrderProductViewModel> customersOrders { get; set; }
        public List<CustomerOrderProductViewModel> customersOrdersWithReturnGoods { get; set; }
        public bool IsReturnProduct { get; set; }
    }
}

DailyBasket.Franchisee/Areas/Sale/Models/ViewModels/FranchiseeOrderProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DailyBasket.Franchisee.Areas.Sale.Models.ViewModels
{
    public class CustomerOrderProductViewModel
    {
        public ulong Id { get; set; }
        public string ProductName { get; set; }
        public float Quantity { get; set; }
        public double TotalAmount { get; set; }
        public string Expiry_Date { get; set; }
        public float Mrp { get; set; }
        public float Sale_Rate { get; set; }
        public string Barcode { get; set; }
        public ulong IsReturnProduct { get; set; }
        public ulong SpId { get; set; }
        public ulong Cop_Id { get; set; }
    }
}

DailyBasket.Franchisee/Areas/Reports/Controllers/SaleController.cs
using DailyBasket.Franchisee.Areas.ProductMaster.BLL;
using DailyBasket.Franchisee.Areas.Reports.BLL;
using DailyBasket.Franchisee.Areas.Reports.Models;
using DailyBasket.Franchisee.Areas.Reports.Models.ViewModels;
using DailyBasket.Franchisee.Helper;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DailyBasket.Franchisee.Core.Interface.BLL.Reports;
using DailyBasket.Franchisee.Core.Model.Report.Sales;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using System.Web.UI;
using System.Web.UI.WebControls;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;

namespace DailyBasket.Franchisee.Areas.Reports.Controllers
{
    public class SaleController : Controller
    {
        SalesReportBLL SalesReportBLL = new SalesReportBLL();
        public ActionResult Sales()
        {
            BindPurchaseReportDropdownList();
            return View();
        }
        [HttpPost]
        public ActionResult Sales(SalesReportList SalesReportList)
        {
            BindPurchaseReportDropdownList();
            var rptname = (SalesReportList.Report).ToString();

            switch (rptname)
            {
                case "BillWise":
                    return RedirectToAction("BillWise");
                case "DateWiseCustomerOrder":
                    return RedirectToAction("DateWiseCustomerOrder");
                case "ProductWiseSales":
                    return RedirectToAction("ProductWiseSales");

                default:
                    return RedirectToAction("Sales");
            }

        }

        [HttpGet]
        public ActionResult BillWise()
        {
            return PartialView("BillWiseSales");
        }

        [HttpGet]
        public ActionResult DateWiseCustomerOrder()
        {
            return PartialView("DateWiseCustomerOrder");
        }
        [HttpGet]
        public ActionResult ProductWiseSales()
        {
            ViewBag.ProductDdlList = new ProductBLL().GetActiveProductListDdl();
            return PartialView("ProductWiseSales");
        }

        public byte[] GetPDF(string pHTML)
        {
            byte[] bPDF = null;

            var ms = new MemoryStream();
            var txtReader = new StringReader(pHTML);

            // 1: create object of a itextsharp document class  
            var doc = new Document(PageSize.A4, 25, 25, 25, 25);

            // 2: we create a itextsharp pdfwriter that listens to the document and directs a XML-stream to a file  
            var oPdfWriter = PdfWriter.GetInstance(doc, ms);

            // 3: we create a worker parse the document  
            var htmlWorker = new HTMLWorker(doc);

            // 4: we open document and start the worker on the document  
            doc.Open();
            htmlWorker.StartDocument();

            // 5: parse the html into the document  
            htmlWorker.Parse(txtReader);

            // 6: close the document and the worker  
            htmlWorker.EndDocument();
            htmlWorker.Close();
            doc.Close();

            bPDF = ms.ToArray();

            return bPDF;
        }

        public string RenderRazorViewToString(dynamic viewModel, string viewName)
        {

            ViewData["viewModel"] = viewModel;

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);

                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);

                return sw.GetStringBuilder().ToString();
            }
        }

        [HttpPost]
        public ActionResult productWiseSalesModel(string Submit, string From_Date, string To_Date, uint ProductId = 0)
        {
            switch (Submit)
            {
                case "Export To Excel":
                    DataTable productWiseSales = null;
                    productWiseSales = SalesReportBLL.GetProductWiseSalesReportListforExcel(From_Date, To_Date, ProductId, SessionManager.CurrentUserId);
                    using (XLWorkbook wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(productWiseSales, "productWiseSales");
                        wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                        wb.Style.Font.Bold = true;

                        Response.Clear();
                        Response.Buffer = true;
                        Response.Charset = "";
                        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        Response.AddHeader("content-disposition", "attachment;filename=ProductWise Sales Report.xlsx");

                        using (MemoryStream MyMemoryStream = new MemoryStream())
                        {
                            wb.SaveAs(MyMemoryStream);
                            MyMemoryStream.WriteTo(Response.OutputStream);
                            Response.Flush();
                            Response.End();
                        }
                    }
                    return RedirectToAction("ProductWiseSales");
                default:
                    ProductWiseSalesModel productWiseSalesModel = null;
                    productWiseSalesModel = SalesReportBLL.GetProductWiseSalesReportList(From_Date, To_Date, ProductId, SessionManager.CurrentUserId);
                    var HTMLContent = RenderRazorViewToString(productWiseSalesModel, "ProductWiseSalesData");
                    var bytes = GetPDF(HTMLContent);

                    using (MemoryStream input = new MemoryStream(bytes))
                    {

                        var reader = new PdfReader(input);

                        Response.ContentType = "application/pdf";
                        Response.AddHeader("content-disposition", "attachment;filename=ProductWise Sales Report.pdf");
                        Response.Cache.SetCacheability(HttpCacheability.NoCache);
                        Response.BinaryWrite(bytes);
                        Response.End();

                    }
                    return RedirectToAction("ProductWiseSales");
            }
        }
        [HttpPost]
        public ActionResult ProductWiseSales(string From_Date, string To_Date, uint ProductId = 0)
        {
            return RedirectToAction("ProductWiseSales");
        }

        [HttpPost]
        public ActionResult BillWise(string From_Date, string To_Date, string Submit)
        {
            switch (Submit)
            {
                case "Export To Excel":
                    DataTable billWiseSales = null;
                    billWiseSales = SalesReportBLL.GetBillWiseSalesListForExcel(From_Date, To_Date, SessionManager.CurrentUserId);
                    using (XLWorkbook wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(billWiseSales, "Customers");
                        wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                        wb.Style.Font.Bold = true;

                        Response.Clear();
                        Response.Buffer = true;
                        Response.Charset = "";
                        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        Response.AddHeader("content-disposition", "attachment;filename=Billwise Sales Report.xlsx");

                        using (MemoryStream MyMemoryStream = new MemoryStream())
                        {
                            wb.SaveAs(MyMemoryStream);
                            MyMemoryStream.WriteTo(Response.OutputStream);
                            Response.Flush();
                            Response.End();
                        }
                    }
                    return RedirectToAction("BillWise");
                default:
                    BillWiseSalesModel billWiseSalesModel = null;
                    billWiseSalesModel = SalesReportBLL.GetBillWiseSalesList(From_Date, To_Date, SessionManager.CurrentUserId);
                    var HTMLContent = RenderRazorViewToString(billWiseSalesModel, "BillWise");
                    var bytes = GetPDF(HTMLContent);
                    using (MemoryStream input = new MemoryStream(bytes))
                    {
                        var reader = new PdfReader(input);
                        Response.ContentType = "application/pdf";
                        Response.AddHeader("content-disposition", "attachment;filename=Billwise Sales Report.pdf");
                        Response.Cache.SetCacheability(HttpCacheability.NoCache);
                        Response.BinaryWrite(bytes);
                        Response.End();
                    }
                    return RedirectToAction("BillWise");
            }
            //return RedirectToAction("BillWise");
        }

        [HttpPost]
        public ActionResult DateWiseCustomerOrderSalesModel(string From_Date, string To_Date, string Submit)
        {
            switch (Submit)
            {
                case "Export To Excel":
                    DataTable dateWiseCustomerOrderSales = null;
                    dateWiseCustomerOrderSales = SalesReportBLL.GetDateWiseCustomerOrderListforExcel(From_Date, To_Date, SessionManager.CurrentUserId);
                    using (XLWorkbook wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(dateWiseCustomerOrderSales, "dateWiseCustomerOrderSales");
                        wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                        wb.Style.Font.Bold = true;

DailyBasket.Franchisee/Areas/Reports/Views/Sale/BillWiseSales.cshtml
@model DailyBasket.Franchisee.Areas.Reports.Models.ViewModels.SalesReportList
@{
    ViewBag.Title = "BillWise Sales Report";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header text-center "><h1>BillWise Sales Report</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("BillWise", "Sale", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("SubmitType", "Temperary");
                    <div class="box-body">
                        <div class="form-group">
                           @Html.Label("Report Type", "Report Type", htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.Report, null, htmlAttributes: new { @class = "form-control", @readonly = "readonly", @placeholder = "BillWise" })
                            @Html.ValidationMessageFor(model => model.Report, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.From_Date, htmlAttributes: new { @class = "control-label col-md-4" })

                            @Html.EditorFor(model => model.From_Date, new { htmlAttributes = new { @class = "form-control datepicker", @data_inputmask = "'alias':'dd-mm-yyyy'", @onchange = "validateBillDate()", @required = true, @placeholder = "Select From Date" } })
                            @Html.ValidationMessageFor(model => model.From_Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.To_Date, htmlAttributes: new { @class = "control-label col-md-4" })

                            @Html.EditorFor(model => model.To_Date, new { htmlAttributes = new { @class = "form-control datepicker", @data_inputmask = "'alias':'dd-mm-yyyy'", @onchange = "validateBillDate()", @required = true, @placeholder = "Select To Date" } })
                            @Html.ValidationMessageFor(model => model.To_Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-md-offset-3 col-md-4">
                            <input type="submit" name="submit" id="exporttoexcel" value="Export To Excel" class="btn btn-block btn-primary btn-info" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Export To PDF" class="btn btn-primary btn-primary" formtarget="_blank"/>
                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

DailyBasket.Franchisee/Areas/Reports/Views/Sale/DateWiseCustomerOrder.cshtml
@model DailyBasket.Franchisee.Areas.Reports.Models.ViewModels.SalesReportList
@{
    ViewBag.Title = "DateWise Sales Report";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header text-center "><h1>DateWise Sales Report</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("dateWiseCustomerOrderSalesModel", "Sale", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("SubmitType", "Temperary");
                    <div class="box-body">
                        <div class="form-group">
                            @Html.Label("Report Type", "Report Type", htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.Report, null, htmlAttributes: new { @class = "form-control", @readonly = "readonly", @placeholder = "DateWiseCustomerOrder" })
                            @Html.ValidationMessageFor(model => model.Report, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.From_Date, htmlAttributes: new { @class = "control-label col-md-4" })

                            @Html.EditorFor(model => model.From_Date, new { htmlAttributes = new { @class = "form-control datepicker", @data_inputmask = "'alias':'dd-mm-yyyy'", @onchange = "validateBillDate()", @required = true, @placeholder = "Select From Date" } })
                            @Html.ValidationMessageFor(model => model.From_Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.To_Date, htmlAttributes: new { @class = "control-label col-md-4" })

                            @Html.EditorFor(model => model.To_Date, new { htmlAttributes = new { @class = "form-control datepicker", @data_inputmask = "'alias':'dd-mm-yyyy'", @onchange = "validateBillDate()", @required = true, @placeholder = "Select To Date" } })
                            @Html.ValidationMessageFor(model => model.To_Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-md-offset-3 col-md-4">
                            <input type="submit" name="submit" id="exporttoexcel" value="Export To Excel" class="btn btn-block btn-primary btn-info" />
                        </div>
                        <div class="form-group">

                            <input type="submit" value="Export To PDF" class="btn btn-primary btn-primary" formtarget="_blank" />

                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

DailyBasket.Franchisee/Areas/Reports/Views/Sale/ProductWiseSales.cshtml
@model DailyBasket.Franchisee.Areas.Reports.Models.ViewModels.SalesReportList
@{
    ViewBag.Title = "Product Wise Sales Report";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header text-center "><h1>Product Wise Sales Report</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("productWiseSalesModel", "Sale", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("SubmitType", "Temperary");
                    <div class="box-body">
                        <div class="form-group">
                           @Html.Label("Report Type", "Report Type", htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Report, null, htmlAttributes: new { @class = "form-control", @readonly = "readonly", @placeholder = "ProductWiseSales" })
                        @Html.ValidationMessageFor(model => model.Report, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">

                           @Html.Label("ProductId", "Product Name", htmlAttributes: new { @class = "control-label" })
                           @Html.TextBox("SelectProductId", null, htmlAttributes: new { @class = "form-control", @placeholder = "All" })
                           @Html.DropDownList("ProductId", ViewBag.ProductDdlList != null ? ViewBag.ProductDdlList as SelectList : Enumerable.Empty<SelectListItem>(), "Select Product Name", htmlAttributes: new { @class = "form-control hide-form-field" })<!--hide-form-field-->
                           @Html.ValidationMessage("ProductId", "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.From_Date, htmlAttributes: new { @class = "control-label col-md-4" })

                            @Html.EditorFor(model => model.From_Date, new { htmlAttributes = new { @class = "form-control datepicker", @data_inputmask = "'alias':'dd-mm-yyyy'", @onchange = "validateBillDate()", @required = true, @placeholder = "Select From Date" } })
                            @Html.ValidationMessageFor(model => model.From_Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.To_Date, htmlAttributes: new { @class = "control-label col-md-4" })

                            @Html.EditorFor(model => model.To_Date, new { htmlAttributes = new { @class = "form-control datepicker", @data_inputmask = "'alias':'dd-mm-yyyy'", @onchange = "validateBillDate()", @required = true, @placeholder = "Select To Date" } })
                            @Html.ValidationMessageFor(model => model.To_Date, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-md-offset-3 col-md-4">
                            <input type="submit" name="submit" id="exporttoexcel" value="Export To Excel" class="btn btn-block btn-primary btn-info" />
                        </div>
                        <div class="form-group">

                            <input type="submit" value="Export To PDF" class="btn btn-primary btn-primary" formtarget="_blank"/>


                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@Scripts.Render("~/bundles/script/async/Purchase/purchase-sale-entry-validation")
@Scripts.Render("~/bundles/script/async/Purchase/pop-validatations-form")


<script>
    debugger;

    var jsonProductList = @Html.Raw(Json.Encode(@ViewBag.ProductDdlList));
    debugger;
</script>

DailyBasket.Franchisee/Areas/Reports/Views/Sale/Sales.cshtml
@model DailyBasket.Franchisee.Areas.Reports.Models.ViewModels.SalesReportList
@{
    ViewBag.Title = "Sales Reports";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header text-center "><h1>Sales Reports</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("Sales", "Sale", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        <div class="form-group">
                            @Html.Label("Report Type", "Report Type", htmlAttributes: new { @class = "control-label" })

                            @Html.DropDownListFor(model => model.Report, ViewBag.PurchaseReportDdlList != null ? ViewBag.PurchaseReportDdlList as SelectList : Enumerable.Empty<SelectListItem>(), "Select Report Type", htmlAttributes: new { @class = "form-control", @required = true, @id = "rptdropdown" })
                            @Html.ValidationMessageFor(model => model.Report, "", new { @class = "text-danger" })
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="col-md-offset-4 col-md-4">
                                <input type="submit" value="OK" class="btn btn-primary btn btn-block btn-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->