DailyBasket.Franchisee/Areas/Purchase/Controllers/PurchaseOrderController.cs
using DailyBasket.Franchisee.Areas.Purchase.BLL;
using DailyBasket.Franchisee.Core.Enum;
using DailyBasket.Franchisee.Core.Interface.BLL.Purchase;
using DailyBasket.Franchisee.Core.Model.Purchase;
using DailyBasket.Franchisee.Helper;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Franchisee.Areas.Purchase.Controllers
{
    [Authorize]
    public class PurchaseOrderController : Controller
    {
        // private IPurchaseProduct iPurchaseProduct = new PurchaseProductBLL();
        IPurchaseProduct iPurchaseProductBLL;
        public PurchaseOrderController()
        {
            iPurchaseProductBLL = new PurchaseProductBLL();
        }

    

        private void BindPurchaseProductViewDdl()
        {
            ViewBag.ProductDdlList = new PurchaseProductBLL().GetActiveProductListDdl();
        }

   
        //code for add purchase order

        [HttpGet]
        public ActionResult AddPurchaseProductOrder()
        {
            ulong poId = iPurchaseProductBLL.AddPurchaseOrder(SessionManager.CurrentUserId);
            if (poId != 0)
            {
                TempData["poId"] = poId;
                return RedirectToAction("AddPurchaseProduct");
            }
            return RedirectToAction("MyPurchaseOrders");
        }

        [HttpGet]
        public ActionResult AddPurchaseProduct()
        {
            ulong poId = Convert.ToUInt32(TempData["poId"]);
            POProductModel poProductModel = new POProductModel();
            if (poId != 0)
            {
                poProductModel.POPProductList = iPurchaseProductBLL.GetPurchaseOrderProductListToCart(poId);
                poProductModel.Id = poId;
                BindPurchaseProductViewDdl();
                return View("AddPurchaseProductOrder", poProductModel);
            }
            return RedirectToAction("MyPurchaseOrders");  // return to myorders List
        }

        [HttpPost]
        public ActionResult AddPurchaseProduct(POProductModel pOProductModel)
        {
            if (ModelState.IsValid)
            {
                if(pOProductModel != null)
                {
                    if (iPurchaseProductBLL.AddPurchaseProductOrder(pOProductModel) != 0)
                    {
                        TempData["Message"] = "Product added successfully.";
                        TempData["CssClass"] = "text-success";
                    }
                    else
                    {
                        TempData["Message"] = "Oops error Occured, Please try again!";
                        TempData["CssClass"] = "text-danger";
                    }
                    TempData["poId"] = pOProductModel.Id;
                    return RedirectToAction("AddPurchaseProduct");
                }
            }
            return RedirectToAction("MyPurchaseOrders");    // redirect to my order list;
        }

        [HttpGet]
        public ActionResult DeletePurchaseProduct(ulong poId = 0, ulong prodId = 0)
        {
            if (poId != 0 && prodId != 0)
            {
                if(iPurchaseProductBLL.DeletePurchaseProduct(poId, prodId) != 0)
                {
                    TempData["Message"] = "Product deleted successfully.";
                    TempData["CssClass"] = "text-success";
                }
                else
                {
                    TempData["Message"] = "product not deleted successfully, Please try again!";
                    TempData["CssClass"] = "text-danger";
                }
            }
            TempData["poId"] = poId;
            return RedirectToAction("AddPurchaseProduct");
        }

        [HttpPost]
        public ActionResult AddPurchaseProductOrder(ulong poId = 0)
        {
            if (poId != 0)
            {
                if (iPurchaseProductBLL.UpdateSubmitTypeofPOP(poId) != 0)
                {
                    return RedirectToAction("MyPurchaseOrders");
                }
            }
            TempData["poId"] = poId;
            return RedirectToAction("AddPurchaseProduct");
        }

        //List of Purchase Orders

        [HttpGet]
        public ActionResult MyPurchaseOrders()
        {
            List<POProductModel> poProductModel = iPurchaseProductBLL.GetPurchaseOrders(SessionManager.CurrentUserId);
            return View(poProductModel);
        }

        [HttpGet]
        public ActionResult PurchaseOrderDetails(ulong poId = 0)
        {
            if(poId != 0)
            {
                POProductModel poProductModel = iPurchaseProductBLL.GetPurchaseProducts(poId);
                return View(poProductModel);
            }
            return View();
        }

        public ActionResult DeliveredOrders()
        {
            ViewBag.MethodName = "DeliveredOrder";
            ViewBag.PageTitle = "Delivered Franchisee Orders";
            return View("FranchiseeOrders", GetFranchiseeOrders(OrderStatus.Delivered));
        }

        public ActionResult CancelledOrders()
        {
            ViewBag.MethodName = "CancelledOrder";
            ViewBag.PageTitle = "Cancelled Franchisee Orders";
            return View("FranchiseeOrders", GetFranchiseeOrders(OrderStatus.Cancelled));
        }
        
        public ActionResult DeliveredOrder(ulong foId = 0)
        {
            ViewBag.PageTitle = "Delivered Customer Order";
            POProductModel poProductModel = GetFranchiseeOrder(OrderStatus.Delivered, foId);
            if (poProductModel == null)
                return RedirectToAction("DeliveredOrders");
            poProductModel.Status = OrderStatus.Delivered;
            return View("FranchiseeOrder", poProductModel);
        }

        public ActionResult CancelledOrder(ulong foId = 0)
        {
            ViewBag.PageTitle = "Cancelled Customer Order";

            POProductModel poProductModel = GetFranchiseeOrder(OrderStatus.Cancelled, foId);
            if (poProductModel == null)
                return RedirectToAction("CancelledOrders");
            poProductModel.Status = OrderStatus.Cancelled;
            return View("FranchiseeOrder", poProductModel);
        }
        
        private List<POProductModel> GetFranchiseeOrders(OrderStatus orderStatus)
        {
            return iPurchaseProductBLL.GetFranchiseeOrders(orderStatus, SessionManager.CurrentUserId, SubmitType.Permanent);
        }

        private POProductModel GetFranchiseeOrder(OrderStatus orderStatus, ulong coId)
        {
            return iPurchaseProductBLL.GetFranchiseeOrder(coId, SessionManager.CurrentUserId, orderStatus);
        }
    }
} 

DailyBasket.Franchisee/Areas/Purchase/Views/PurchaseOrder/AddPurchaseProductOrder.cshtml
@model  DailyBasket.Franchisee.Core.Model.Purchase.POProductModel 
@*@model IEnumerable<DailyBasket.Franchisee.Core.Model.Purchase.POProductModel>*@
@{
    ViewBag.Title = "Add Purchase Product Order";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
    HttpCookie poCookie = null;
    if (HttpContext.Current.Request.Cookies["PurchaseOrderCookie"] != null)
    {
        poCookie = HttpContext.Current.Request.Cookies["PurchaseOrderCookie"];
    }
}

<section class="content-header text-center">
    <h1>Add Purchase Product Order</h1>
</section>
<!-- / Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <div class="box box-warning">
                <div class="clearfix"></div>
                <!-- /.box-header -->
                <div class="box-body">

                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Bill No.</label>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>0001</label>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Bill Date</label>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>@DateTime.Now.ToString()</label>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Vender Name</label>
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div class="form-group">
                            <label>DailyBasket Warehouse</label>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <hr />
                    @if (TempData["Message"] != null)
                    {
                        <div class="col-lg-12 text-center">
                            <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                        </div>
                    }
                    @using (Html.BeginForm("AddPurchaseProduct", "PurchaseOrder", FormMethod.Post, htmlAttributes: new { @onsubmit = "return validatePop()" }))
                    {
                        @Html.AntiForgeryToken()
                        @*@Html.Hidden("PurchaseOrderId", TempData["PoId"].ToString())*@
                        @Html.HiddenFor(model => model.Id)
                        @*@Html.Hidden("PurchaseOrderId", poModelCookie["PoId"].ToString())
                            @Html.Hidden("SubmitType", "Temperary")*@
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="form-group">

                                    @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label" })

                                    @Html.TextBox("SelectProductId", null, htmlAttributes: new { @class = "form-control", @required = true, @placeholder = "Select Product Name" })
                                    @Html.DropDownListFor(model => model.ProductId, ViewBag.ProductDdlList != null ? ViewBag.ProductDdlList as SelectList : Enumerable.Empty<SelectListItem>(), "Select Product Name", htmlAttributes: new { @class = "form-control hide-form-field" })
                                    @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @type = "number", @class = "form-control", @placeholder = "Enter Product Quantity", @required = "true" } })
                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-md-2">
                            <br />
                            <input type="submit" name="submit" id="submit" value="Add Product" class="btn btn-block btn-primary btn-success" />
                        </div>
                        @*<div class="col-md-2">
                            <br />
                            <input type="submit" name="submit" id="submit" value="Submit Order" class="btn btn-block btn-primary btn-success" />
                        </div>*@
                        <div class="clearfix"></div>
                        <hr />
                    }

                    <section class="content" >
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="box">
                                    <div class="box-body">
                                        <table id="example2" class="table table-bordered table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Sr. No</th>
                                                    <th>Product Name</th>
                                                    <th>Quantity</th>
                                                    <th>Remove</th>
                                                </tr>
                                            </thead>
                                            <tbody id="reloadsection">
                                               @if(Model.POPProductList != null && Model.POPProductList.Any())
                                               {

                                                   var index = 1;
                                                   foreach (var poprodDetails in Model.POPProductList)
                                                   {
                                                        <tr>
                                                            <td>@(index++)</td>
                                                            <td>@poprodDetails.ProdName </td>
                                                            <td>@poprodDetails.Quantity </td>
                                                            <td><a href="@Url.Action("DeletePurchaseProduct", "PurchaseOrder", new { Area ="Purchase", poId = @poprodDetails.PoId, @prodId = @poprodDetails.ProdId })" class="fa fa-trash-o btn-xs btn-danger" onclick="return confirm('Are you sure you want to delete this item?');" title="Delete" id="deleteProduct"></a></td>
                                                        </tr>
                                                   }
                                               }
                                               else
                                               {
                                                    <tr>
                                                        <td colspan="4"><label class="text-danger">No Record Found</label></td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                            @using (Html.BeginForm("AddPurchaseProductOrder", "PurchaseOrder", FormMethod.Post))
                                            {
                                                if (Model.POPProductList != null && Model.POPProductList.Any())
                                                {
                                                    @Html.Hidden("poId", TempData["poId"])
                                                    <br/>
                                                    <div class="col-md-2 pull-right">
                                                        <input type="submit" name="submit" id="submit" value="Submit Order" class="btn btn-block btn-primary btn-success" />
                                                    </div>
                                                }
                                            }
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                                <!-- /.box -->

                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </section>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>
@Scripts.Render("~/bundles/script/async/productmaster/product-autopopulate-list-with-jquery")
@Scripts.Render("~/bundles/script/async/purchase/pop-delete-validation-form")
<script>
    var jsonProductList = @Html.Raw(Json.Encode(@ViewBag.ProductDdlList));
</script>

DailyBasket.Franchisee/Areas/Purchase/Views/PurchaseOrder/FranchiseeOrder.cshtml
@model DailyBasket.Franchisee.Core.Model.Purchase.POProductModel
@using DailyBasket.Franchisee.Core.Enum;
@{
    ViewBag.Title = "FranchiseeOrder";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header text-center">
    <h1><label>@ViewBag.PageTitle</label></h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-sm-2 pull-right">
            @Html.Hidden("OrderStatus", (uint)Model.Status)
            @*<button id="printorder" class="btn btn-sm btn-block alert-info">Print</button>*@
        </div>

        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    @if (Model != null)
                    {
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th colspan="2" class="text-center">Franchisee&nbsp;Details</th>
                                    <th colspan="2" class="text-center">Order&nbsp;Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>Vendor&nbsp;Name</th>
                                    <td>@Model.VendorName</td>
                                    <th class="seperator-left">Order&nbsp;Id / Refer. Order Id</th>
                                    <td class="seperator-right">@Model.BillNo/  @Model.Id</td>
                                </tr>
                                <tr>
                                    <th class="seperator-left">Order&nbsp;Date</th>
                                    <td class="seperator-right">@Model.OrderDate</td>
                                    <th class="seperator-left">Order&nbsp;Amount</th>
                                    <td class="seperator-right"><i class="fa fa-inr"></i> @Model.TotalBillAmount</td>
                                </tr>
                            </tbody>
                        </table>
                    }
                    <div class="clearfix"></div>
                    <hr />
                    <br />
                    @if (TempData["Message"] != null)
                    {
                        <div class="col-lg-12 text-center">
                            <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                        </div>
                    }


                    @using (Html.BeginForm("ChangeCurrentOrderStatus", "FranchiseeOrders", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.BillNo)

                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Sr.No.</th>
                                    <th>Product Name</th>
                                    <th>Quantity</th>
                                    <th>MRP</th>
                                    <th>Purchase Rate</th>
                                    <th>Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.POPProductList.Any() || Model.POPProductList.Count > 0)
                                {
                                    var index = 1;
                                    foreach (var Order in Model.POPProductList)
                                    {
                                        <tr>
                                            <td>@(index++)</td>
                                            <td>@Order.ProdName</td>
                                            <td>@Order.Quantity</td>
                                            <td><i class="fa fa-inr"></i> @Order.MRP</td>
                                            <td><i class="fa fa-inr"></i> @Order.Price</td>
                                            <td><i class="fa fa-inr"></i> @Order.TotalAmount</td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="6"><label class="text-danger">No Record Found</label></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    <br />
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

@Scripts.Render("~/bundles/script/sale/print-customer-orders")

DailyBasket.Franchisee/Areas/Purchase/Views/PurchaseOrder/FranchiseeOrders.cshtml
@model IEnumerable<DailyBasket.Franchisee.Core.Model.Purchase.POProductModel>

@using DailyBasket.Franchisee.Core.Enum;

@{
    ViewBag.Title = "FranchiseeOrders";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header text-center">

    <h1> <label>@ViewBag.PageTitle</label></h1>

</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Sr.No.</th>
                                <th>Bill No.</th>
                                <th>Vendor Name</th>
                                <th>Order Date</th>
                                <th>Total Bill Amount</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                var index = 1;
                                foreach (var order in Model)
                                {

                                    <tr>
                                        <td>@(index++) </td>
                                        <td>@order.BillNo</td>
                                        <td>@order.VendorName</td>
                                        <td>@order.OrderDate</td>
                                        <td><i class="fa fa-inr"></i>  @order.TotalBillAmount</td>
                                        <td class="text-center fontset">
                                            <a href="@Url.Action(ViewBag.MethodName, "PurchaseOrder", new { Area = "Purchase", @foId = order.BillNo })" id="ViewOrder" class="fa fa-eye btn-xs btn-info" title="View"></a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="6"><label class="text-danger">No Records Found</label></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

DailyBasket.Franchisee/Areas/Purchase/Views/PurchaseOrder/MyPurchaseOrders.cshtml
@model IEnumerable<DailyBasket.Franchisee.Core.Model.Purchase.POProductModel>
@{
    ViewBag.Title = "GetPurchaseOrdersList";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}


<section class="content-header text-center">
    <h1>View Purchase Orders</h1>
</section>
<!-- / Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <div class="box box-warning">
                <div class="clearfix"></div>
                <!-- /.box-header -->
                <div class="box-body">
                    <!-- Main content -->
                    <section class="content">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="box">
                                    <div class="box-body">
                                        <table id="example2" class="table table-bordered table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Sr.No.</th>
                                                    <th>Bill No</th>
                                                    <th>Vendor Name</th>
                                                    <th>OrderDate</th>
                                                    <th class="text-center">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model != null && Model.Any())
                                                {
                                                    var index = 1;
                                                    foreach (var PODetails in Model)
                                                    {

                                                        <tr>
                                                            <td>@(index++)</td>
                                                            <td>@PODetails.BillNo</td>
                                                            <td>@PODetails.VendorName</td>
                                                            <td>@PODetails.OrderDate</td>
                                                            <td class="text-center fontset">
                                                                <a href="@Url.Action("PurchaseOrderDetails", "PurchaseOrder", new { Area ="Purchase", poId = PODetails.BillNo})" class="fa fa-eye btn-xs btn-info" title="View"></a>
                                                            </td>
                                                        </tr>
                                                    }
                                                }
                                                else
                                                {
                                                    <tr>
                                                        <td colspan="8"><label class="text-danger">No Record Found</label></td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                                <!-- /.box -->

                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </section>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>